//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace Shop.EntityModel {

	[JsonObject(MemberSerialization.OptIn)]
	public partial class CustomerCategory {

		[JsonProperty, Column(IsIdentity = true)]
		public long AutoID { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string BillType { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime? CloseDate { get; set; }

		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string CloseUser { get; set; } = string.Empty;

		//[JsonProperty]
		//public Guid? CustomerCategory { get; set; }

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string CustomerCategoryID { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string CustomerCategoryName { get; set; } = string.Empty;

		[JsonProperty]
		public Guid? CustomerCategoryParentID { get; set; }

		[JsonProperty]
		public Guid ID { get; set; }

		[JsonProperty]
		public bool? IsStop { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string Level { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime? MakeDate { get; set; }

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string Maker { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string Mender { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime? ModifyDate { get; set; }

		[JsonProperty]
		public int RowNo { get; set; }

	}

}
