//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace Shop.EntityModel {

	[JsonObject(MemberSerialization.OptIn)]
	public partial class Customer {

		[JsonProperty, Column(DbType = "varchar(255)")]
		public string AbbrName { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(255)")]
		public string Address { get; set; } = string.Empty;

		[JsonProperty]
		public Guid? Area { get; set; }

		[JsonProperty, Column(DbType = "nvarchar(100)")]
		public string AttrInfo { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string Audit { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime? AuditDate { get; set; }

		[JsonProperty, Column(IsIdentity = true)]
		public long AutoID { get; set; }

		[JsonProperty, Column(DbType = "varchar(255)")]
		public string BankAccount { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(255)")]
		public string BankName { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string BillType { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(255)")]
		public string BondedSupervisionType { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(255)")]
		public string Brand { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(255)")]
		public string BusinessCertificate { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(255)")]
		public string BusinessLicense { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(255)")]
		public string BusinessScope { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(400)")]
		public string BuyGoods { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(255)")]
		public string CashAsset { get; set; } = string.Empty;

		[JsonProperty]
		public Guid? CityID { get; set; }

		[JsonProperty]
		public DateTime? CloseDate { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string CloseUser { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(255)")]
		public string Code { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "decimal(38,2)")]
		public decimal? CommissionRate { get; set; }

		[JsonProperty, Column(DbType = "varchar(255)")]
		public string ContactPhone { get; set; } = string.Empty;

		[JsonProperty]
		public Guid? CountryID { get; set; }

		[JsonProperty]
		public Guid? CountyID { get; set; }

		[JsonProperty, Column(DbType = "date")]
		public DateTime? CreditLimit { get; set; }

		[JsonProperty, Column(DbType = "varchar(255)")]
		public string CreditRating { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(255)")]
		public string Currency { get; set; } = string.Empty;

		[JsonProperty]
		public Guid? CustomerCategoryID { get; set; }

		[JsonProperty, Column(DbType = "varchar(255)")]
		public string DeliveryAddress { get; set; } = string.Empty;

		[JsonProperty]
		public Guid? DepartmentID { get; set; }

		[JsonProperty, Column(DbType = "decimal(38,2)")]
		public decimal? DepositRate { get; set; }

		[JsonProperty, Column(DbType = "varchar(255)")]
		public string Destination { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(255)")]
		public string Email { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(255)")]
		public string EnglishAddress { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(255)")]
		public string EnglishName { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(255)")]
		public string Fax { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime? FirstCheckDate { get; set; }

		[JsonProperty, Column(DbType = "varchar(255)")]
		public string Grade { get; set; } = string.Empty;

		[JsonProperty]
		public Guid ID { get; set; }

		[JsonProperty]
		public bool? IFCreditLimit { get; set; }

		[JsonProperty]
		public bool? IFLineCredit { get; set; }

		[JsonProperty, Column(DbType = "nvarchar(200)")]
		public string InCompanyName { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(255)")]
		public string Industry { get; set; } = string.Empty;

		[JsonProperty]
		public bool? IsStop { get; set; }

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string LargeRegions { get; set; } = string.Empty;

		[JsonProperty]
		public string LatentDemand { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(255)")]
		public string LegalPerson { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "decimal(38,2)")]
		public decimal? LineCredit { get; set; }

		[JsonProperty, Column(DbType = "varchar(255)")]
		public string MajorCarriers { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime? MakeDate { get; set; }

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string Maker { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string Mender { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(255)")]
		public string Merchandiser { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(255)")]
		public string MnemonicCode { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime? ModifyDate { get; set; }

		[JsonProperty, Column(DbType = "varchar(255)")]
		public string Name { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string NamePYCode { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(255)")]
		public string OfficialWeb { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(255)")]
		public string PostCode { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "decimal(38,2)")]
		public decimal? PremiumRate { get; set; }

		[JsonProperty, Column(DbType = "varchar(255)")]
		public string PrimaryContact { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(500)")]
		public string Product { get; set; } = string.Empty;

		[JsonProperty]
		public Guid? ProvinceID { get; set; }

		[JsonProperty, Column(DbType = "varchar(255)")]
		public string ReceiptType { get; set; } = string.Empty;

		[JsonProperty]
		public string RegionalManager { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "decimal(38,2)")]
		public decimal? RegisteredCapital { get; set; }

		[JsonProperty, Column(DbType = "varchar(255)")]
		public string RegistrationCode { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(500)")]
		public string Remark { get; set; } = string.Empty;

		[JsonProperty]
		public int RowNo { get; set; }

		[JsonProperty, Column(DbType = "varchar(255)")]
		public string SaleArea { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(255)")]
		public string SalesMan { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(100)")]
		public string Source { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime? StopDate { get; set; }

		[JsonProperty, Column(DbType = "nvarchar(30)")]
		public string StopOper { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string SubRegions { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "decimal(38,2)")]
		public decimal? SurplusLimit { get; set; }

		[JsonProperty, Column(DbType = "varchar(255)")]
		public string TAXID { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "decimal(38,2)")]
		public decimal? TaxRate { get; set; }

		[JsonProperty, Column(DbType = "varchar(255)")]
		public string Text { get; set; } = string.Empty;

		[JsonProperty]
		public int? TimeLimitDay { get; set; }

		[JsonProperty, Column(DbType = "varchar(255)")]
		public string TransportNode { get; set; } = string.Empty;

	}

}
