//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace Shop.EntityModel {

	[JsonObject(MemberSerialization.OptIn)]
	public partial class SalesOrder {

		[JsonProperty, Column(DbType = "date")]
		public DateTime? AcceptDate { get; set; }

		[JsonProperty, Column(DbType = "nvarchar(30)")]
		public string AddAudit { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime? AddAuditDate { get; set; }

		[JsonProperty, Column(DbType = "decimal(38,2)")]
		public decimal? AluminumPrice { get; set; }

		[JsonProperty, Column(DbType = "decimal(38,8)")]
		public decimal? AluminumPrice_USA { get; set; }

		[JsonProperty, Column(DbType = "date")]
		public DateTime? AluminumPriceDate { get; set; }

		[JsonProperty]
		public Guid? AluminumPriceDateID { get; set; }

		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string AluminumPriceValuation { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string Approval { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(30)")]
		public string Approval2 { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime? Approval2Date { get; set; }

		[JsonProperty]
		public DateTime? ApprovalDate { get; set; }

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string Audit { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime? AuditDate { get; set; }

		[JsonProperty, Column(IsIdentity = true)]
		public long AutoID { get; set; }

		[JsonProperty, Column(Name = "belongcompany")]
		public string Belongcompany { get; set; } = string.Empty;

		[JsonProperty]
		public Guid? BelongsCustomer { get; set; }

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string BillCode { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string BillType { get; set; } = string.Empty;

		[JsonProperty]
		public bool? CalculatedAluminumPrice { get; set; }

		[JsonProperty]
		public DateTime? CheckDate { get; set; }

		[JsonProperty, Column(DbType = "nvarchar(30)")]
		public string CheckOper { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime? CloseDate { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string CloseUser { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime? ConfirmedDate { get; set; }

		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string ConfirmOperator { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string ContractNo { get; set; } = string.Empty;

		[JsonProperty]
		public Guid? CountryID { get; set; }

		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string Currency { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(100)")]
		public string CustomerBillCode { get; set; } = string.Empty;

		[JsonProperty]
		public Guid? CustomerID { get; set; }

		[JsonProperty, Column(DbType = "varchar(255)")]
		public string CustomerPO { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string DeliveryAddress { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string DeliveryMethod { get; set; } = string.Empty;

		[JsonProperty]
		public Guid? DepartmentID { get; set; }

		[JsonProperty, Column(DbType = "decimal(38,2)")]
		public decimal? DepositAmount { get; set; }

		[JsonProperty, Column(DbType = "decimal(38,2)")]
		public decimal? DepositAmount1 { get; set; }

		[JsonProperty, Column(DbType = "decimal(38,2)")]
		public decimal? DepositAmount2 { get; set; }

		[JsonProperty]
		public bool? DepositFlag { get; set; }

		[JsonProperty, Column(DbType = "decimal(38,2)")]
		public decimal? DepositPrice { get; set; }

		[JsonProperty, Column(DbType = "nvarchar(30)")]
		public string DepositRatio1 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(30)")]
		public string DepositRatio2 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "decimal(38,3)")]
		public decimal? DepositWeight { get; set; }

		[JsonProperty, Column(DbType = "decimal(38,8)")]
		public decimal? ExchangeRate { get; set; }

		[JsonProperty]
		public DateTime? ExtrusionEndDate { get; set; }

		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string ExtrusionEndOper { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime? FinishDate { get; set; }

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string FinishOper { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime? FirstAuditDate { get; set; }

		[JsonProperty, Column(Name = "freight", DbType = "nvarchar(30)")]
		public string Freight { get; set; } = string.Empty;

		[JsonProperty, Column(Name = "freight1", DbType = "nvarchar(50)")]
		public string Freight1 { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(100)")]
		public string GlassThickness { get; set; } = string.Empty;

		[JsonProperty]
		public Guid ID { get; set; }

		[JsonProperty]
		public bool? IfTranToK3 { get; set; }

		[JsonProperty]
		public bool? IsOrderCancel { get; set; }

		[JsonProperty]
		public bool? IsOrderSuspend { get; set; }

		[JsonProperty]
		public bool? IsProcessingTrade { get; set; }

		[JsonProperty]
		public bool? IsRefuse { get; set; }

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string LargeRegions { get; set; } = string.Empty;

		[JsonProperty]
		public int? LimitedProductionQuantity { get; set; }

		[JsonProperty]
		public DateTime? MakeDate { get; set; }

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string Maker { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string ManualNumber { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "decimal(38,8)")]
		public decimal? MembraneFee { get; set; }

		[JsonProperty, Column(DbType = "nvarchar(500)")]
		public string Memo { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string Mender { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string Merchandiser { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime? ModifyDate { get; set; }

		[JsonProperty, Column(DbType = "nvarchar(30)")]
		public string OnlineAudited { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(200)")]
		public string OpenMode { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "decimal(38,8)")]
		public decimal? OperateFee { get; set; }

		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string OrderCategory { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "date")]
		public DateTime? OrderDate { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string OrderType { get; set; } = string.Empty;

		[JsonProperty]
		public Guid? PackingID { get; set; }

		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string PaymentMethod { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "date")]
		public DateTime? PlanFinishDate { get; set; }

		[JsonProperty, Column(DbType = "nvarchar(30)")]
		public string PreAudit { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime? PreAuditDate { get; set; }

		[JsonProperty]
		public int? PrintCount { get; set; }

		[JsonProperty]
		public DateTime? ProductionEndDate { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string ProductionEndOper { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string Project { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(500)")]
		public string RefuseReason { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(1000)")]
		public string Remark { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime? ResetDateK3 { get; set; }

		[JsonProperty, Column(DbType = "nvarchar(30)")]
		public string ResetOperK3 { get; set; } = string.Empty;

		[JsonProperty]
		public int RowNo { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string Salesman { get; set; } = string.Empty;

		[JsonProperty]
		public Guid? SalesManWareHouseAreaID { get; set; }

		[JsonProperty, Column(DbType = "nvarchar(10)")]
		public string Sign { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string Specialpricing { get; set; } = string.Empty;

		[JsonProperty]
		public int? States { get; set; }

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string SubRegions { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "decimal(38,2)")]
		public decimal? Subscription { get; set; }

		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string Telephonist { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "decimal(38,2)")]
		public decimal? TotalAmount { get; set; }

		[JsonProperty]
		public Guid? TruckID { get; set; }

		[JsonProperty]
		public bool? WithoutApproval { get; set; }

		[JsonProperty]
		public bool? WithTax { get; set; }

	}

}
