//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace Shop.EntityModel {

	[JsonObject(MemberSerialization.OptIn)]
	public partial class Surface {

		[JsonProperty]
		public Guid? ASurfaceID { get; set; }

		[JsonProperty, Column(IsIdentity = true)]
		public long AutoID { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string BillType { get; set; } = string.Empty;

		[JsonProperty]
		public Guid? BSurfaceID { get; set; }

		[JsonProperty]
		public DateTime? CloseDate { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string CloseUser { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string ColorPlate { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(200)")]
		public string ColorPricingClass { get; set; } = string.Empty;

		[JsonProperty]
		public Guid? CraftID { get; set; }

		[JsonProperty, Column(DbType = "nvarchar(200)")]
		public string FactoryColor { get; set; } = string.Empty;

		[JsonProperty]
		public Guid ID { get; set; }

		[JsonProperty]
		public bool? IsStop { get; set; }

		[JsonProperty]
		public DateTime? MakeDate { get; set; }

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string Maker { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(100)")]
		public string ManufacturerPowder { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string Mender { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime? ModifyDate { get; set; }

		[JsonProperty, Column(DbType = "image")]
		public byte[] Picture { get; set; }

		[JsonProperty, Column(DbType = "nvarchar(500)")]
		public string Remark { get; set; } = string.Empty;

		[JsonProperty]
		public int RowNo { get; set; }

		[JsonProperty]
		public DateTime? StopDate { get; set; }

		[JsonProperty, Column(DbType = "nvarchar(30)")]
		public string StopOper { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "decimal(38,2)")]
		public decimal? SupportTolerance { get; set; }

		[JsonProperty]
		public Guid? SurfaceCategoryID { get; set; }

		[JsonProperty, Column(DbType = "varchar(255)")]
		public string SurfaceCode { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(255)")]
		public string SurfaceName { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(200)")]
		public string SurfaceTreatmentMaterials { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(20)")]
		public string SurfaceType { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(255)")]
		public string Text { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string TheFactoryLogo { get; set; } = string.Empty;

	}

}
