//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace Shop.EntityModel
{

	[JsonObject(MemberSerialization.OptIn)]
	public partial class Vendor {

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string AbbrName { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(300)")]
		public string Address { get; set; } = string.Empty;

		[JsonProperty]
		public Guid? Area { get; set; }

		[JsonProperty, Column(IsIdentity = true)]
		public long AutoID { get; set; }

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string BankAccount { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(300)")]
		public string BankName { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string BillType { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string BondedSupervisionType { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string Brand { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string BusinessCertificate { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string BusinessLicense { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(500)")]
		public string BusinessScope { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string CashAsset { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "date")]
		public DateTime? CheckDate { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string CheckOper { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime? CloseDate { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string CloseUser { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string Code { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "decimal(38,8)")]
		public decimal? CommissionRate { get; set; }

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string ContactPhone { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string Country { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "date")]
		public DateTime? CreateDate { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string CreateOper { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string CreditRating { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string Currency { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string Department { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string Destination { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string Email { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(200)")]
		public string EnglishAddress { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string EnglishName { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string Fax { get; set; } = string.Empty;

		[JsonProperty]
		public bool? HeatVendor { get; set; }

		[JsonProperty]
		public Guid ID { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string Industry { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string Invoices { get; set; } = string.Empty;

		[JsonProperty]
		public bool? IsStop { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string LegalPerson { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string MajorCarriers { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime? MakeDate { get; set; }

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string Maker { get; set; } = string.Empty;

		[JsonProperty]
		public bool? MaterialOut { get; set; }

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string Mender { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string MnemonicCode { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime? ModifyDate { get; set; }

		[JsonProperty]
		public bool? MouldProduct { get; set; }

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string Name { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "decimal(38,8)")]
		public decimal? OnTimeDelivery { get; set; }

		[JsonProperty]
		public bool? OutsourcingVendor { get; set; }

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string Phone { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string PostCode { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "decimal(38,8)")]
		public decimal? PremiumRate { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string PrimaryContact { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "decimal(38,8)")]
		public decimal? RegisteredCapital { get; set; }

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string RegistrationCode { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(500)")]
		public string Remark { get; set; } = string.Empty;

		[JsonProperty]
		public int RowNo { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string SalesMan { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string ShippingMethod { get; set; } = string.Empty;

		[JsonProperty]
		public bool? SpareParts { get; set; }

		[JsonProperty]
		public DateTime? StopDate { get; set; }

		[JsonProperty, Column(DbType = "nvarchar(30)")]
		public string StopOper { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string TAXID { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "decimal(38,8)")]
		public decimal? TaxRate { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string TransportNode { get; set; } = string.Empty;

		[JsonProperty]
		public Guid? VendorCategoryID { get; set; }

		[JsonProperty, Column(DbType = "varchar(200)")]
		public string WebSite { get; set; } = string.Empty;

	}

}
