//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace Shop.EntityModel {

	[JsonObject(MemberSerialization.OptIn)]
	public partial class MaterialStock {

		/// <summary>
		/// 金额
		/// </summary>
		[JsonProperty, Column(DbType = "decimal(38,10)")]
		public decimal Amount { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string BarCode { get; set; } = string.Empty;

		/// <summary>
		/// 批号
		/// </summary>
		[JsonProperty, Column(DbType = "varchar(50)")]
		public string BatNo { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "decimal(38,10)")]
		public decimal CostPrice { get; set; }

		[JsonProperty]
		public Guid ID { get; set; }

		[JsonProperty]
		public DateTime? InventoryDate { get; set; }

		[JsonProperty, Column(DbType = "nvarchar(500)")]
		public string InventoryRemark { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime? LastInstoreDate { get; set; }

		[JsonProperty, Column(DbType = "decimal(38,10)")]
		public decimal? LastUnitPrice { get; set; }

		/// <summary>
		/// 库位
		/// </summary>
		[JsonProperty]
		public Guid MaterialWareHouseID { get; set; }

		[JsonProperty]
		public Guid? MaterialWarehouseShelfNumberID { get; set; }

		/// <summary>
		/// 货品ID
		/// </summary>
		[JsonProperty]
		public Guid ProductID { get; set; }

		/// <summary>
		/// 数量
		/// </summary>
		[JsonProperty, Column(DbType = "decimal(38,10)")]
		public decimal Quantity { get; set; }

	}

}
