//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace Shop.EntityModel {

	[JsonObject(MemberSerialization.OptIn)]
	public partial class MaterialWarehouse {

		[JsonProperty, Column(DbType = "decimal(38,4)")]
		public decimal? Area { get; set; }

		[JsonProperty, Column(IsIdentity = true)]
		public long AutoID { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string BillType { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime? CloseDate { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string CloseUser { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string Code { get; set; } = string.Empty;

		[JsonProperty]
		public bool? Fitting { get; set; }

		[JsonProperty, Column(DbType = "decimal(38,2)")]
		public decimal? Height { get; set; }

		[JsonProperty]
		public Guid ID { get; set; }

		[JsonProperty]
		public bool? IsStop { get; set; }

		[JsonProperty, Column(DbType = "decimal(38,2)")]
		public decimal? Length { get; set; }

		[JsonProperty]
		public DateTime? MakeDate { get; set; }

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string Maker { get; set; } = string.Empty;

		[JsonProperty]
		public int? MaxDepositQuantity { get; set; }

		[JsonProperty, Column(DbType = "decimal(38,4)")]
		public decimal? MaxDepositVolume { get; set; }

		[JsonProperty, Column(DbType = "decimal(38,4)")]
		public decimal? MaxDepositWeight { get; set; }

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string Mender { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime? ModifyDate { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string Name { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string Region { get; set; } = string.Empty;

		[JsonProperty]
		public int RowNo { get; set; }

		[JsonProperty]
		public DateTime? StopDate { get; set; }

		[JsonProperty, Column(DbType = "nvarchar(30)")]
		public string StopOper { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "decimal(38,4)")]
		public decimal? Volume { get; set; }

		[JsonProperty, Column(DbType = "decimal(38,2)")]
		public decimal? Width { get; set; }

	}

}
