//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace Shop.EntityModel {

	[JsonObject(MemberSerialization.OptIn)]
	public partial class Product {

		[JsonProperty, Column(IsIdentity = true)]
		public long AutoID { get; set; }

		[JsonProperty, Column(DbType = "nvarchar(30)")]
		public string BarCode { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string BillType { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime? CloseDate { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string CloseUser { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "decimal(38,3)")]
		public decimal? ConversionRate { get; set; }

		[JsonProperty, Column(DbType = "nvarchar(30)")]
		public string CostAccountMethod { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(100)")]
		public string CostClass { get; set; } = string.Empty;

		[JsonProperty]
		public Guid? CostName { get; set; }

		[JsonProperty, Column(DbType = "decimal(38,4)")]
		public decimal? CostPrice { get; set; }

		[JsonProperty]
		public bool? Fitting { get; set; }

		[JsonProperty, Column(DbType = "nvarchar(100)")]
		public string GoodsUse { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(100)")]
		public string HelpCode { get; set; } = string.Empty;

		[JsonProperty]
		public Guid ID { get; set; }

		[JsonProperty, Column(DbType = "decimal(38,8)")]
		public decimal? Inventory { get; set; }

		[JsonProperty]
		public bool? IsReCalc { get; set; }

		[JsonProperty]
		public bool? IsStop { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string IUint { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime? MakeDate { get; set; }

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string Maker { get; set; } = string.Empty;

		[JsonProperty]
		public Guid? MaterialWarehouseShelfNumberID { get; set; }

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string Mender { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime? ModifyDate { get; set; }

		[JsonProperty]
		public Guid? MouldID { get; set; }

		[JsonProperty]
		public string PartsCode { get; set; } = string.Empty;

		[JsonProperty]
		public string PartsName { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "image")]
		public byte[] Picture { get; set; }

		[JsonProperty, Column(DbType = "decimal(38,4)")]
		public decimal? ProcurementPrice { get; set; }

		[JsonProperty]
		public Guid? ProductCategoryID { get; set; }

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string ProductCategoryName { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string ProductCode { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string ProductName { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(100)")]
		public string ProductSpec { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(100)")]
		public string ProductType { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "decimal(38,8)")]
		public decimal? QuantityCeiling { get; set; }

		[JsonProperty, Column(DbType = "decimal(38,8)")]
		public decimal? QuantityFloor { get; set; }

		[JsonProperty]
		public int RowNo { get; set; }

		[JsonProperty, Column(DbType = "decimal(38,4)")]
		public decimal? SellingPrice { get; set; }

		[JsonProperty]
		public DateTime? StopDate { get; set; }

		[JsonProperty, Column(DbType = "nvarchar(30)")]
		public string StopOper { get; set; } = string.Empty;

		[JsonProperty]
		public bool? Tax { get; set; }

		[JsonProperty]
		public string Texture { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string Unit { get; set; } = string.Empty;

		[JsonProperty]
		public Guid? Warehouse { get; set; }

	}

}
